### ISSUE TITLE
Play fails when log set to debug/-vvvv over Mac

### ISSUE THREAD

**Issue by justjais** [cidrblock/conn_shim_action_validation#1]
Play works as expected if the log level is not set to `debug` level (i.e. until -vvv) but fails when log set to debug/-vvvv over Mac. Below is the traceback:

```
conn_shim_action_validation git:(main) ✗ ansible-playbook -i inventory.yaml try_github.yaml -vvvv
ansible-playbook [core 2.11.2] 
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/Users/sjaiswal/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.9/site-packages/ansible
  ansible collection location = /Users/sjaiswal/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible-playbook
  python version = 3.9.5 (default, May  4 2021, 03:33:11) [Clang 12.0.0 (clang-1200.0.32.29)]
  jinja version = 3.0.1
  libyaml = True
Using /etc/ansible/ansible.cfg as config file
setting up inventory plugins
host_list declined parsing /Users/sjaiswal/Sumit/conn_shim_action_validation/inventory.yaml as it did not pass its verify_file() method
script declined parsing /Users/sjaiswal/Sumit/conn_shim_action_validation/inventory.yaml as it did not pass its verify_file() method
Parsed /Users/sjaiswal/Sumit/conn_shim_action_validation/inventory.yaml inventory source with yaml plugin
Loading collection cidrblock.conn_test from /Users/sjaiswal/Sumit/conn_shim_action_validation/collections/ansible_collections/cidrblock/conn_test
Loading callback plugin default of type stdout, v2.0 from /usr/local/lib/python3.9/site-packages/ansible/plugins/callback/default.py
Skipping callback 'default', as we already have a stdout callback.
Skipping callback 'minimal', as we already have a stdout callback.
Skipping callback 'oneline', as we already have a stdout callback.

PLAYBOOK: try_github.yaml ************************************************************************************************************************************************************************************
Positional arguments: try_github.yaml
verbosity: 4
connection: smart
timeout: 10
become_method: sudo
tags: ('all',)
inventory: ('/Users/sjaiswal/Sumit/conn_shim_action_validation/inventory.yaml',)
forks: 5
1 plays in try_github.yaml

PLAY [gh_api_endpoint] ***************************************************************************************************************************************************************************************
META: ran handlers

TASK [gh get user] *******************************************************************************************************************************************************************************************
task path: /Users/sjaiswal/Sumit/conn_shim_action_validation/try_github.yaml:4
<gh_api_endpoint> attempting to start connection
<gh_api_endpoint> using connection plugin cidrblock.conn_test.github
Found ansible-connection at path /usr/local/bin/ansible-connection
<gh_api_endpoint> local domain socket does not exist, starting it
<gh_api_endpoint> control socket path is /Users/sjaiswal/.ansible/pc/eb28af9cfa
<gh_api_endpoint> 
The full traceback is:
Traceback (most recent call last):
  File "/usr/local/bin/ansible-connection", line 103, in start
    self.connection.set_options(var_options=variables)
  File "/Users/sjaiswal/Sumit/conn_shim_action_validation/collections/ansible_collections/cidrblock/conn_test/plugins/connection/github.py", line 142, in wrapped
    msg = self._log_with_pid(
  File "/Users/sjaiswal/Sumit/conn_shim_action_validation/collections/ansible_collections/cidrblock/conn_test/plugins/connection/github.py", line 164, in _log_with_pid
    name = subprocess.check_output(
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'ps -p 39498 -o cmd=' returned non-zero exit status 1.
fatal: [gh_api_endpoint]: FAILED! => {
    "msg": "Command 'ps -p 39498 -o cmd=' returned non-zero exit status 1."
}
...ignoring
```

And, the actual `subprocess` exception thrown is:
```
"msg": "'CalledProcessError' object is not callable"
```

**Comment by justjais** [comment]
@cidrblock for mac the supported command is: `ps -p {pid} -o command=`, so `command` instead of `cmd`.

**Comment by cidrblock** [comment]
cool, updated
